### ISSUE TITLE
Pay a RGB invoice failed (contract index missing)

### ISSUE THREAD

**Issue by crisdut** [RGB-WG/rgb-wallet#30]
### Discussed in https://github.com/orgs/RGB-WG/discussions/246

I tried pay a rgb invoice using `rgb cli`, but I receive the following error:

```
[2023-03-30T04:51:09Z DEBUG rgb] Executing command: transfer
thread 'main' panicked at 'error paying invoice: Consigner(InventoryError(InternalInconsistency(Stash(ContractAbsent(ContractId(Array<32>(0e366c92ad6f0dc1c0ae223aacd8b258aef8f2b72bcbd95208449ab205eb3df2)))))))', src/bin/rgb/command.rs:411:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After investigating, I found the reason: 

Into the `consign` method, we tried to get contract_index information (see [here](https://github.com/RGB-WG/rgb-wallet/blob/36d4a451cc61eb5ffc978c272daa80f6177b9435/std/src/persistence/inventory.rs#L419)). However, in no previous step did we fill in this information. 

</div>

**Comment by dr-orlovsky** [comment]
Fixed in https://github.com/RGB-WG/rgb-wallet/commit/2f21496a906c1717b103f83bc5d5c8939322f34a

Will be merged during the release
