### ISSUE TITLE
contract global metadata extraction bug

### ISSUE THREAD

**Issue by zoedberg** [RGB-WG/rgb-wallet#54]
After updating the following dependencies:
- bp-core: 0.10.1 -> 0.10.3
- bp-seals: 0.10.0 -> 0.10.3
- rgb-std: 0.10.0 -> 0.10.2
- rgb-wallet: 0.10.0 -> 0.10.2
- rgb_core: 0.10.1 -> 0.10.3
- strict_encoding: 2.1.1 -> 2.2.1
- strict_types: 1.1.0 -> 1.2.0

I'm no longer able to extract global metadata from the consignment.

Running:
```rust
for global in &contract.iface.global_state {
    if let Ok(values) = contract.global(global.name.clone()) {
        for val in values {
            println!("{} := {}", global.name, val);
        }
    }
}
```

Before updating dependencies I was receiving:
```
Nominal := (ticker=("TICKER"), name=("asset name"), details=~, precision=7)
ContractText := ("RGB 20 asset")
```

After updating dependencies I receive:
```
created := (0)
spec := (naming=(ticker=([68]), name=([68]), details=~), precision=7)
terms := ("")
```

By logging the `contract` object it seems that before updating the dependencies the asset information was visible in the `history` section, while after updating info is no longer visible anywhere in the contract.

**Comment by dr-orlovsky** [comment]
It was fixed yesterday - pls update to the tip of master branch.

Still the metadata now are not strings but int arrays. It is not a bug, but a result of using restricted charset. I am thinking now this can be improved.

**Comment by dr-orlovsky** [comment]
This was the fix: https://github.com/RGB-WG/rgb-wallet/commit/96fe097366e8982d94c207037df14b56c7a361cf
