### ISSUE TITLE
Insufficient state when the state is sufficient

### ISSUE THREAD

**Issue by dr-orlovsky** [RGB-WG/rgb-wallet#67]
Reported by @nicbus:

I have tried the updated code in our regtest sandbox, which uses rgb-contracts (with patched dependencies and a quick fix to have a working issuance).

What I do to check for this issue is:

    issue an asset (2000)
    send some assets (100) from the issuer to a 1st recipient
    send some more assets (200) from the issuer to the same recipient
    send some assets (250) from the 1st recipient to a 2nd recipient

This way I check that the issuer is able to spend the change allocation, which is created via WitnessUtxo, and then that the resulting allocation is itself spendable.

At the moment, step 4 fails when I call rgb transfer with error:

Error: InsufficientState

Original report: https://github.com/RGB-WG/rgb-wallet/issues/55#issuecomment-1591429377
May be related to: https://github.com/RGB-WG/rgb-core/issues/159

**Comment by dr-orlovsky** [comment]
@nicbus did you pay the initial amount (100) and the second one (200) to the same UTXO or different ones? If different, you had to prepare a PSBT which spends both UTXOs, otherwise indeed you won't have enough tokens to pay the invoice (that is what `InsufficientState` means)

**Comment by dr-orlovsky** [comment]
It should be improved. But here you get not an error message with Display but with Debug. Seems like you just unwrap in rgb-lib code. So to have a proper message instead of unwrapping/expecting you need to handle error prints and reporting with some code using Display

**Comment by nicbus** [comment]
here I'm not using rgb-lib but rgb-contracts. specifically, I receive the `InsufficientState` error after calling `rgb transfer`

**Comment by dr-orlovsky** [comment]
So than error has to be n non-unrapped in rgb-contracts, not here. This would display the full verbose message with explanation.

I can open the issue there - and I assume this one can be closed?

**Comment by dr-orlovsky** [comment]
Closed in d90868a769987aa278214d06d13da98e698ea702
