### ISSUE TITLE
Lnpbp4Mismatch non-deterministic error

### ISSUE THREAD

**Issue by zoedberg** [RGB-WG/rgb-wallet#83]
Executing rgb-lib tests I've found a test that sometimes fails (around once every 10 successful runs).

The test issues an asset, sends it to a second wallet, which then sends it to a third wallet. When the second wallet calls `accept_transfer` to "finalize" the second transfer it (sometimes) fails with a `Lnpbp4Mismatch` error.

**Comment by dr-orlovsky** [comment]
So does this happens with just a single issued asset in all three wallets?

**Comment by zoedberg** [comment]
Nope, sorry I've just noticed that the first wallet issues two assets on the same UTXO, then sends only one to the second wallet.
Instead wallet 2 and 3 are both fresh, they never issued assets.

I'll comment the second issuance and let you know if this detail makes the difference.

**Comment by dr-orlovsky** [comment]
> When the second wallet calls accept_transfer to "finalize" the second transfer

I do not get this part: the second wallet sending the second transfer (to the third wallet) should not call  "accept_transfer". Overall wallet sending transfer doesn't need to accept anything,

**Comment by zoedberg** [comment]
Sorry, I mischecked again. The test sends both assets, not just one. So in order to reproduce this on the sandbox I guess we should implement batch transfers also on rgb-wallet.

**Comment by zoedberg** [comment]
> Overall wallet sending transfer doesn't need to accept anything

Call to accept transfer was there for RGB 0.9 and we just forgot to remove it when updating to RGB 0.10. But it seems that normally that call doesn't hurt. Anyway I'll try to remove it and see if something changes

**Comment by dr-orlovsky** [comment]
1. Yes, the call to `accept_transfer` by a sending party must be a non-operation (otherwise there is a bug).
2. Is there any way how I can run your test in rgb-lib, reproduce the issue and debug it?

**Comment by zoedberg** [comment]
> Is there any way how I can run your test in rgb-lib, reproduce the issue and debug it?

Yes, but first I need to clean the code a bit in order to make the branch public. I'll do that on Monday and then let you know when you can try it yourself

**Comment by dr-orlovsky** [comment]
@zoedberg pls run your tests with this branch: https://github.com/LNP-BP/client_side_validation/pull/127 (add it to `patches.crates-io` section if `rgb-lib` `Crate.toml`)

I think I was able to figure out the case with a piece of paper and some drawings of different scenarios.

**Comment by zoedberg** [comment]
fixed with https://github.com/LNP-BP/client_side_validation/pull/129
