### ISSUE TITLE
Add witness transaction to consignment terminals

### ISSUE THREAD

**Issue by dr-orlovsky** [RGB-WG/rgb-wallet#87]
For multiparty protocols where the transaction can't be deterministically generated from the state data (like in CoinJoin, atomic swaps) we need to transfer (partial) bitcoin transaction. Instead passing it alongside the consignment, I propose to put it right into consignment terminals (one optional tx per terminal).

**Comment by fedsten** [comment]
Does this provide any benefit? Passing the PSBT alongside the consignment or inside the consignment seems equivalent to me.

**Comment by dr-orlovsky** [comment]
1) it is not PSBT, just a transaction
2) there might be multiple transactions (for instance in a consignment dealing with several operations

From the UI perspective it will be harder to ask user to copy/paste multiple pieces instead of one - plus there will be a requirement on how to associate transaction with specific bundles/state transitions - so no, it is not equivalent.

**Comment by crisdut** [comment]
@dr-orlovsky 

Could this be useful for controlling transitions on LN channels?

**Comment by dr-orlovsky** [comment]
Nope, since you do not need to send the consignment to update the channel. It only may be useful for funding dually-funded channels (or multi-finded channel factories)
